---
name: Data-FormValidator-Filters-Image
version: 0.30
author:
  - Cees Hek <ceeshek@gmail.com>
abstract: Filter that allows you to shrink incoming image uploads when using Data::FormValidator
license: perl
requires:
  CGI: 0
  Data::FormValidator: 0
  File::Basename: 0
  File::Spec: 0
  Image::Magick: 0
  MIME::Types: 0
recommends:
  HTTP::Request::Common: 0
  Image::Info: 0
provides:
  Data::FormValidator::Filters::Image:
    file: lib/Data/FormValidator/Filters/Image.pm
    version: 0.30
generated_by: Module::Build version 0.2611
